# Generated by Django 5.1.6 on 2025-03-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('user_type', models.CharField(choices=[('usuario', 'Usuario'), ('conductor', 'Conductor')], max_length=10)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
